
/* globals GPXmap */

"use strict";

GPXmap.addItem("gc0001.gpx", `
<?xml version="1.0" encoding="utf-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0" creator="CacheWolf" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/1 http://www.groundspeak.com/cache/1/0/1/cache.xsd  ">
<name>Waypoints for Cache Listings, Generated by CacheWolf</name>
<desc>This is an individual cache generated from Geocaching.com</desc>
<author>Various users from geocaching.com and/or opencaching.de</author>
<email>contact@cachewolf.de</email>
<url>http://www.cachewolf.de/</url>
<urlname>CacheWolf - Paperless Geocaching</urlname>
<time>2025-08-07T07:00:00Z</time>
<keywords>cache, geocache, waypoints</keywords>
  <wpt lat="52.5196" lon="13.40687">
    <time>2025-08-07T07:00:00Z</time>
    <name>GC0001</name>
    <desc>Neptune Fountain (Neptunbrunnen) by benchmarko, Traditional Cache (1.5/1.0)</desc>
    <url>https://en.wikipedia.org/wiki/Neptune_Fountain_(Berlin)</url>
    <urlname>Neptune Fountain (Berlin)</urlname>
    <sym>Geocache</sym>
    <type>Geocache|Traditional Cache</type>
    <groundspeak:cache id="1" available="True" archived="False" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1">
      <groundspeak:name>Neptune Fountain (Neptunbrunnen)</groundspeak:name>
      <groundspeak:placed_by>Wikipedia</groundspeak:placed_by>
      <groundspeak:owner id="00001">Wikipedia</groundspeak:owner>
      <groundspeak:type>Traditional Cache</groundspeak:type>
      <groundspeak:container>virtual</groundspeak:container>
      <groundspeak:attributes>
      </groundspeak:attributes>
      <groundspeak:difficulty>1.5</groundspeak:difficulty>
      <groundspeak:terrain>1.0</groundspeak:terrain>
      <groundspeak:country>Germany</groundspeak:country>
      <groundspeak:state>Berlin</groundspeak:state>
      <groundspeak:short_description html="True">A monumental fountain in central Berlin, built in 1891.</groundspeak:short_description>
      <groundspeak:long_description html="True">&lt;b&gt;Note: This is an hypothetical cache which may not exist!&lt;/b&gt;&lt;br&gt;The Neptune Fountain (German: Neptunbrunnen) in Berlin was built in 1891 and designed by Reinhold Begas. The Roman god Neptune stands at the center, surrounded by four women representing the main rivers of Prussia at the time: Elbe, Rhine, Vistula, and Oder. The fountain was moved to its current location between St. Mary's Church and Rotes Rathaus in 1969. Diameter: 18 m, Height: 10 m.&lt;br /&gt;
      Source: &lt;a href="https://en.wikipedia.org/wiki/Neptune_Fountain_(Berlin)"&gt;Neptune Fountain (Berlin)&lt;/a&gt;&lt;br /&gt;
      German: &lt;a href="https://de.wikipedia.org/wiki/Neptunbrunnen_(Berlin)"&gt;Neptunbrunnen (Berlin)&lt;/a&gt;&lt;br /&gt;
      Coordinates: N 52° 31.176 E 013° 24.412&lt;br /&gt;
      &lt;details>&lt;summary>Solver&lt;/summary>&lt;div class="gc_solver">cls()&lt;br/&gt;
&lt;/div>&lt;/details>
</groundspeak:long_description>
      <groundspeak:encoded_hints>No hint</groundspeak:encoded_hints>
      <groundspeak:logs>
      </groundspeak:logs>
      <groundspeak:travelbugs>
      </groundspeak:travelbugs>
    </groundspeak:cache>
  </wpt>
  <wpt lat="52.52015" lon="13.40642">
    <time>2025-08-07T07:00:00Z</time>
    <name>PK0001</name>
    <desc>Parking area for Neptune Fountain (Neptunbrunnen)</desc>
    <sym>Parking Area</sym>
    <type>Waypoint|Parking Area</type>
  </wpt>
</gpx>
`);
